### ISSUE TITLE
Semantic highlights are not working.

### ISSUE THREAD

**Issue by Hitesh-Aggarwal** [NTBBloodbath/sweetie.nvim#5]
![image](https://user-images.githubusercontent.com/95736269/232112261-fe49a178-1a0f-4e2f-ae8d-e239837041b5.png)

I have clangd setup as the lsp server. I am on Neovim 0.9 and semantic highlights are not working. I have tried with tokyonight and catppuccin themes, on those the semantic highlights work as expected. I have also tried to hack on the colorscheme myself but I was unable to find the problem.

**Comment by NTBBloodbath** [comment]
Hey, sorry for the late reply!

This is an odd behavior, how is it supposed to look like? I really want to dig on it as semantic highlighting is important.

Also if you are trying to modify sweetie's highlighting groups it's encouraged to use `vim.api.nvin_set_hl` Lua API instead of `:hi` command.

Cheers

**Comment by Hitesh-Aggarwal** [comment]
![image](https://user-images.githubusercontent.com/95736269/233820656-df7420ef-0403-4a66-9865-7b74c2172d1e.png)
It looks like this...
I am using catppuccin colorscheme in above screenshot.
The variables passed as argument appear in different color than those declared locally.

**Comment by fitrh** [comment]
You can fix this by linking `@lsp.type.parameter` to tree-sitter `@parameter`


The problem is:

- `@lsp.type.parameter` linked to `@identifier`
- `@identifier` is not set

So the `@lsp.type.parameter` has the same color as `@lsp.type.variable`, which is a link to `@none`, which is an empty group definition.

**Comment by NTBBloodbath** [comment]
Hey, thank you so much for this input!

Could you please open a PR to address this behavior? I would be glad to merge it as soon as possible :D
